name: medicare
description: Doctor Appointment App
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_storage: ^11.0.7
  fluttertoast: ^8.1.2
  cloud_firestore: ^4.2.0
  flutter_map: ^0.14.0
  simple_animations: ^4.1.0
  supercharged: ^2.1.1
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
  pin_code_fields: ^7.4.0
  ionicons: ^0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/